
local affinity = require("affinity")
local race_name = require("race_name")

---@param deity number
---@return number # 0: none, 1: spirit (magic), 2: fire, 3: water (cold), 4: (poison), 5: air (disease)
function deityAffinity(deity)
	if deity == 140 or deity == 396 then
		return affinity.EARTH -- agnostic
	end
	if deity == 201 then
		return affinity.EARTH -- bertox
	end
	if deity == 202 then
		return affinity.EARTH -- brell
	end
	if deity == 203 then
		return affinity.FIRE -- cazic fire
	end
	if deity == 204 then
		return affinity.AIR -- erollisi air
	end
	if deity == 205 then
		return affinity.SPIRIT -- bristlebane spirit
	end
	if deity == 206 then
		return affinity.FIRE -- innoruuk fire
	end
	if deity == 207 then
		return affinity.WATER -- karana water
	end
	if deity == 208 then
		return affinity.SPIRIT -- mithaniel spirit
	end
	if deity == 209 then
		return affinity.WATER -- prexus water
	end
	if deity == 210 then
		return affinity.AIR -- quellious air
	end
	if deity == 211 then
		return affinity.WATER -- rallos water
	end
	if deity == 212 then
		return affinity.SPIRIT -- rodect spirit
	end
	if deity == 213 then
		return affinity.FIRE -- solusek fire
	end
	if deity == 214 then
		return affinity.FIRE -- tribunal fire
	end
	if deity == 215 then
		return affinity.EARTH -- tunare
	end
	if deity == 216 then
		return affinity.AIR -- veeshan air
	end
	return 0
end

local ZoneAffinity = {
	{ID = Zone.abysmal, Affinity = affinity.WATER},
	{ID = Zone.acrylia, Affinity = affinity.SPIRIT},
	{ID = Zone.airplane, Affinity = affinity.AIR},
	{ID = Zone.akanon, Affinity = affinity.WATER},
	{ID = Zone.akheva, Affinity = affinity.EARTH},
	{ID = Zone.alkabormare, Affinity = affinity.AIR},
	{ID = Zone.anguish, Affinity = affinity.AIR},
	{ID = Zone.apprentice, Affinity = affinity.WATER},
	{ID = Zone.arcstone, Affinity = affinity.SPIRIT},
	{ID = Zone.arelis, Affinity = affinity.EARTH},
	{ID = Zone.arena, Affinity = affinity.EARTH},
	{ID = Zone.arena2, Affinity = affinity.EARTH},
	{ID = Zone.argath, Affinity = affinity.WATER},
	{ID = Zone.arthicrex, Affinity = affinity.EARTH},
	{ID = Zone.arttest, Affinity = affinity.WATER},
	{ID = Zone.ashengate, Affinity = affinity.FIRE},
	{ID = Zone.atiiki, Affinity = affinity.EARTH},
	{ID = Zone.aviak, Affinity = affinity.AIR},
	{ID = Zone.barindu, Affinity = affinity.SPIRIT},
	{ID = Zone.barren, Affinity = affinity.WATER},
	{ID = Zone.barter, Affinity = affinity.WATER},
	{ID = Zone.bazaar, Affinity = affinity.WATER},
	{ID = Zone.beastdomain, Affinity = affinity.AIR},
	{ID = Zone.befallen, Affinity = affinity.SPIRIT},
	{ID = Zone.befallenb, Affinity = affinity.SPIRIT},
	{ID = Zone.beholder, Affinity = affinity.WATER},
	{ID = Zone.bertoxtemple, Affinity = affinity.WATER},
	{ID = Zone.blackburrow, Affinity = affinity.WATER},
	{ID = Zone.blacksail, Affinity = affinity.WATER},
	{ID = Zone.bloodfields, Affinity = affinity.WATER},
	{ID = Zone.bloodmoon, Affinity = affinity.WATER},
	{ID = Zone.bothunder, Affinity = affinity.WATER},
	{ID = Zone.breedinggrounds, Affinity = affinity.WATER},
	{ID = Zone.brellsarena, Affinity = affinity.WATER},
	{ID = Zone.brellsrest, Affinity = affinity.WATER},
	{ID = Zone.brellstemple, Affinity = affinity.WATER},
	{ID = Zone.broodlands, Affinity = affinity.WATER},
	{ID = Zone.buriedsea, Affinity = affinity.WATER},
	{ID = Zone.burningwood, Affinity = affinity.WATER},
	{ID = Zone.butcher, Affinity = affinity.EARTH},
	{ID = Zone.cabeast, Affinity = affinity.WATER},
	{ID = Zone.cabwest, Affinity = affinity.WATER},
	{ID = Zone.cauldron, Affinity = affinity.WATER},
	{ID = Zone.causeway, Affinity = affinity.WATER},
	{ID = Zone.cazicthule, Affinity = affinity.WATER},
	{ID = Zone.chambersa, Affinity = affinity.WATER},
	{ID = Zone.chambersb, Affinity = affinity.WATER},
	{ID = Zone.chambersc, Affinity = affinity.WATER},
	{ID = Zone.chambersd, Affinity = affinity.WATER},
	{ID = Zone.chamberse, Affinity = affinity.WATER},
	{ID = Zone.chambersf, Affinity = affinity.WATER},
	{ID = Zone.chapterhouse, Affinity = affinity.WATER},
	{ID = Zone.charasis, Affinity = affinity.WATER},
	{ID = Zone.chardok, Affinity = affinity.EARTH},
	{ID = Zone.chardokb, Affinity = affinity.SPIRIT},
	{ID = Zone.citymist, Affinity = affinity.WATER},
	{ID = Zone.cityofbronze, Affinity = affinity.WATER},
	{ID = Zone.clz, Affinity = affinity.WATER},
	{ID = Zone.cobaltscar, Affinity = affinity.WATER},
	{ID = Zone.codecay, Affinity = affinity.SPIRIT},
	{ID = Zone.commonlands, Affinity = affinity.FIRE},
	{ID = Zone.commons, Affinity = affinity.FIRE},
	{ID = Zone.convorteum, Affinity = affinity.WATER},
	{ID = Zone.coolingchamber, Affinity = affinity.WATER},
	{ID = Zone.corathus, Affinity = affinity.WATER},
	{ID = Zone.corathusa, Affinity = affinity.WATER},
	{ID = Zone.corathusb, Affinity = affinity.WATER},
	{ID = Zone.crescent, Affinity = affinity.WATER},
	{ID = Zone.crushbone, Affinity = affinity.AIR},
	{ID = Zone.cryptofshade, Affinity = affinity.WATER},
	{ID = Zone.crystal, Affinity = affinity.WATER},
	{ID = Zone.crystallos, Affinity = affinity.WATER},
	{ID = Zone.crystalshard, Affinity = affinity.WATER},
	{ID = Zone.cshome, Affinity = affinity.WATER},
	{ID = Zone.dalnir, Affinity = affinity.WATER},
	{ID = Zone.dawnshroud, Affinity = affinity.WATER},
	{ID = Zone.deadbone, Affinity = affinity.WATER},
	{ID = Zone.delvea, Affinity = affinity.WATER},
	{ID = Zone.delveb, Affinity = affinity.WATER},
	{ID = Zone.devastation, Affinity = affinity.WATER},
	{ID = Zone.devastationa, Affinity = affinity.WATER},
	{ID = Zone.direwind, Affinity = affinity.WATER},
	{ID = Zone.discord, Affinity = affinity.WATER},
	{ID = Zone.discordtower, Affinity = affinity.WATER},
	{ID = Zone.drachnidhive, Affinity = affinity.FIRE},
	{ID = Zone.drachnidhivea, Affinity = affinity.FIRE},
	{ID = Zone.drachnidhiveb, Affinity = affinity.FIRE},
	{ID = Zone.drachnidhivec, Affinity = affinity.FIRE},
	{ID = Zone.dragoncrypt, Affinity = affinity.WATER},
	{ID = Zone.dragonscale, Affinity = affinity.WATER},
	{ID = Zone.dragonscaleb, Affinity = affinity.WATER},
	{ID = Zone.dranik, Affinity = affinity.WATER},
	{ID = Zone.dranikcatacombsa, Affinity = affinity.WATER},
	{ID = Zone.dranikcatacombsb, Affinity = affinity.WATER},
	{ID = Zone.dranikcatacombsc, Affinity = affinity.WATER},
	{ID = Zone.dranikhollowsa, Affinity = affinity.WATER},
	{ID = Zone.dranikhollowsb, Affinity = affinity.WATER},
	{ID = Zone.dranikhollowsc, Affinity = affinity.WATER},
	{ID = Zone.draniksewersa, Affinity = affinity.WATER},
	{ID = Zone.draniksewersb, Affinity = affinity.WATER},
	{ID = Zone.draniksewersc, Affinity = affinity.WATER},
	{ID = Zone.draniksscar, Affinity = affinity.WATER},
	{ID = Zone.dreadlands, Affinity = affinity.WATER},
	{ID = Zone.dreadspire, Affinity = affinity.WATER},
	{ID = Zone.droga, Affinity = affinity.WATER},
	{ID = Zone.dulak, Affinity = affinity.WATER},
	{ID = Zone.eastkarana, Affinity = affinity.WATER},
	{ID = Zone.eastkorlach, Affinity = affinity.WATER},
	{ID = Zone.eastkorlacha, Affinity = affinity.WATER},
	{ID = Zone.eastsepulcher, Affinity = affinity.WATER},
	{ID = Zone.eastwastes, Affinity = affinity.WATER},
	{ID = Zone.eastwastesshard, Affinity = affinity.WATER},
	{ID = Zone.echo_, Affinity = affinity.WATER},
	{ID = Zone.ecommons, Affinity = affinity.WATER},
	{ID = Zone.elddar, Affinity = affinity.WATER},
	{ID = Zone.elddara, Affinity = affinity.WATER},
	{ID = Zone.emeraldjungle, Affinity = affinity.WATER},
	{ID = Zone.erudnext, Affinity = affinity.WATER},
	{ID = Zone.erudnint, Affinity = affinity.WATER},
	{ID = Zone.erudsxing, Affinity = affinity.WATER},
	{ID = Zone.erudsxing2, Affinity = affinity.WATER},
	{ID = Zone.everfrost, Affinity = affinity.WATER},
	{ID = Zone.eviltree, Affinity = affinity.WATER},
	{ID = Zone.fallen, Affinity = affinity.WATER},
	{ID = Zone.fearplane, Affinity = affinity.FIRE},
	{ID = Zone.feerrott, Affinity = affinity.WATER},
	{ID = Zone.feerrott2, Affinity = affinity.WATER},
	{ID = Zone.felwithea, Affinity = affinity.EARTH},
	{ID = Zone.felwitheb, Affinity = affinity.EARTH},
	{ID = Zone.ferubi, Affinity = affinity.WATER},
	{ID = Zone.fhalls, Affinity = affinity.WATER},
	{ID = Zone.fieldofbone, Affinity = affinity.SPIRIT},
	{ID = Zone.firiona, Affinity = affinity.EARTH},
	{ID = Zone.foundation, Affinity = affinity.WATER},
	{ID = Zone.freeportacademy, Affinity = affinity.FIRE},
	{ID = Zone.freeportarena, Affinity = affinity.FIRE},
	{ID = Zone.freeportcityhall, Affinity = affinity.FIRE},
	{ID = Zone.freeporteast, Affinity = affinity.FIRE},
	{ID = Zone.freeporthall, Affinity = affinity.FIRE},
	{ID = Zone.freeportmilitia, Affinity = affinity.FIRE},
	{ID = Zone.freeportsewers, Affinity = affinity.FIRE},
	{ID = Zone.freeporttemple, Affinity = affinity.FIRE},
	{ID = Zone.freeporttheater, Affinity = affinity.FIRE},
	{ID = Zone.freeportwest, Affinity = affinity.FIRE},
	{ID = Zone.freporte, Affinity = affinity.SPIRIT},
	{ID = Zone.freportn, Affinity = affinity.FIRE},
	{ID = Zone.freportw, Affinity = affinity.FIRE},
	{ID = Zone.frontiermtns, Affinity = affinity.WATER},
	{ID = Zone.frostcrypt, Affinity = affinity.WATER},
	{ID = Zone.frozenshadow, Affinity = affinity.WATER},
	{ID = Zone.fungalforest, Affinity = affinity.WATER},
	{ID = Zone.fungusgrove, Affinity = affinity.WATER},
	{ID = Zone.gfaydark, Affinity = affinity.WATER},
	{ID = Zone.greatdivide, Affinity = affinity.WATER},
	{ID = Zone.grelleth, Affinity = affinity.WATER},
	{ID = Zone.griegsend, Affinity = affinity.WATER},
	{ID = Zone.grimling, Affinity = affinity.WATER},
	{ID = Zone.grobb, Affinity = affinity.WATER},
	{ID = Zone.growthplane, Affinity = affinity.WATER},
	{ID = Zone.guardian, Affinity = affinity.WATER},
	{ID = Zone.guildhall, Affinity = affinity.WATER},
	{ID = Zone.guildlobby, Affinity = affinity.WATER},
	{ID = Zone.guka, Affinity = affinity.WATER},
	{ID = Zone.gukb, Affinity = affinity.WATER},
	{ID = Zone.gukbottom, Affinity = affinity.EARTH},
	{ID = Zone.gukc, Affinity = affinity.SPIRIT},
	{ID = Zone.gukd, Affinity = affinity.SPIRIT},
	{ID = Zone.guke, Affinity = affinity.SPIRIT},
	{ID = Zone.gukf, Affinity = affinity.SPIRIT},
	{ID = Zone.gukg, Affinity = affinity.SPIRIT},
	{ID = Zone.gukh, Affinity = affinity.SPIRIT},
	{ID = Zone.guktop, Affinity = affinity.AIR},
	{ID = Zone.gunthak, Affinity = affinity.WATER},
	{ID = Zone.gyrospireb, Affinity = affinity.WATER},
	{ID = Zone.gyrospirez, Affinity = affinity.WATER},
	{ID = Zone.halas, Affinity = affinity.WATER},
	{ID = Zone.harbingers, Affinity = affinity.WATER},
	{ID = Zone.hateplane, Affinity = affinity.WATER},
	{ID = Zone.hateplaneb, Affinity = affinity.WATER},
	{ID = Zone.hatesfury, Affinity = affinity.WATER},
	{ID = Zone.highkeep, Affinity = affinity.WATER},
	{ID = Zone.highpass, Affinity = affinity.WATER},
	{ID = Zone.highpasshold, Affinity = affinity.WATER},
	{ID = Zone.highpasskeep, Affinity = affinity.WATER},
	{ID = Zone.hillsofshade, Affinity = affinity.WATER},
	{ID = Zone.hohonora, Affinity = affinity.WATER},
	{ID = Zone.hohonorb, Affinity = affinity.WATER},
	{ID = Zone.hole, Affinity = affinity.WATER},
	{ID = Zone.hollowshade, Affinity = affinity.WATER},
	{ID = Zone.housegarden, Affinity = affinity.WATER},
	{ID = Zone.iceclad, Affinity = affinity.WATER},
	{ID = Zone.icefall, Affinity = affinity.WATER},
	{ID = Zone.ikkinz, Affinity = affinity.WATER},
	{ID = Zone.illsalin, Affinity = affinity.WATER},
	{ID = Zone.illsalina, Affinity = affinity.WATER},
	{ID = Zone.illsalinb, Affinity = affinity.WATER},
	{ID = Zone.illsalinc, Affinity = affinity.WATER},
	{ID = Zone.inktuta, Affinity = affinity.WATER},
	{ID = Zone.innothule, Affinity = affinity.WATER},
	{ID = Zone.innothuleb, Affinity = affinity.WATER},
	{ID = Zone.jaggedpine, Affinity = affinity.WATER},
	{ID = Zone.jardelshook, Affinity = affinity.WATER},
	{ID = Zone.kael, Affinity = affinity.WATER},
	{ID = Zone.kaelshard, Affinity = affinity.WATER},
	{ID = Zone.kaesora, Affinity = affinity.WATER},
	{ID = Zone.kaladima, Affinity = affinity.WATER},
	{ID = Zone.kaladimb, Affinity = affinity.WATER},
	{ID = Zone.karnor, Affinity = affinity.WATER},
	{ID = Zone.katta, Affinity = affinity.WATER},
	{ID = Zone.kattacastrum, Affinity = affinity.WATER},
	{ID = Zone.kedge, Affinity = affinity.WATER},
	{ID = Zone.kerraridge, Affinity = affinity.WATER},
	{ID = Zone.kithforest, Affinity = affinity.WATER},
	{ID = Zone.kithicor, Affinity = affinity.WATER},
	{ID = Zone.kodtaz, Affinity = affinity.WATER},
	{ID = Zone.korascian, Affinity = affinity.WATER},
	{ID = Zone.kurn, Affinity = affinity.WATER},
	{ID = Zone.lakeofillomen, Affinity = affinity.WATER},
	{ID = Zone.lakerathe, Affinity = affinity.WATER},
	{ID = Zone.lavastorm, Affinity = affinity.FIRE},
	{ID = Zone.letalis, Affinity = affinity.WATER},
	{ID = Zone.lfaydark, Affinity = affinity.WATER},
	{ID = Zone.lichencreep, Affinity = affinity.WATER},
	{ID = Zone.load, Affinity = affinity.WATER},
	{ID = Zone.load2, Affinity = affinity.WATER},
	{ID = Zone.lopingplains, Affinity = affinity.WATER},
	{ID = Zone.maiden, Affinity = affinity.WATER},
	{ID = Zone.maidensgrave, Affinity = affinity.WATER},
	{ID = Zone.mansion, Affinity = affinity.WATER},
	{ID = Zone.mechanotus, Affinity = affinity.WATER},
	{ID = Zone.mesa, Affinity = affinity.WATER},
	{ID = Zone.mira, Affinity = affinity.WATER},
	{ID = Zone.miragulmare, Affinity = affinity.WATER},
	{ID = Zone.mirb, Affinity = affinity.WATER},
	{ID = Zone.mirc, Affinity = affinity.WATER},
	{ID = Zone.mird, Affinity = affinity.WATER},
	{ID = Zone.mire, Affinity = affinity.WATER},
	{ID = Zone.mirf, Affinity = affinity.WATER},
	{ID = Zone.mirg, Affinity = affinity.WATER},
	{ID = Zone.mirh, Affinity = affinity.WATER},
	{ID = Zone.miri, Affinity = affinity.WATER},
	{ID = Zone.mirj, Affinity = affinity.WATER},
	{ID = Zone.mischiefplane, Affinity = affinity.WATER},
	{ID = Zone.mistmoore, Affinity = affinity.WATER},
	{ID = Zone.misty, Affinity = affinity.WATER},
	{ID = Zone.mistythicket, Affinity = affinity.WATER},
	{ID = Zone.mmca, Affinity = affinity.WATER},
	{ID = Zone.mmcb, Affinity = affinity.WATER},
	{ID = Zone.mmcc, Affinity = affinity.WATER},
	{ID = Zone.mmcd, Affinity = affinity.WATER},
	{ID = Zone.mmce, Affinity = affinity.WATER},
	{ID = Zone.mmcf, Affinity = affinity.WATER},
	{ID = Zone.mmcg, Affinity = affinity.WATER},
	{ID = Zone.mmch, Affinity = affinity.WATER},
	{ID = Zone.mmci, Affinity = affinity.WATER},
	{ID = Zone.mmcj, Affinity = affinity.WATER},
	{ID = Zone.monkeyrock, Affinity = affinity.WATER},
	{ID = Zone.moors, Affinity = affinity.WATER},
	{ID = Zone.morellcastle, Affinity = affinity.WATER},
	{ID = Zone.mseru, Affinity = affinity.WATER},
	{ID = Zone.nadox, Affinity = affinity.WATER},
	{ID = Zone.najena, Affinity = affinity.WATER},
	{ID = Zone.natimbi, Affinity = affinity.WATER},
	{ID = Zone.necropolis, Affinity = affinity.WATER},
	{ID = Zone.nedaria, Affinity = affinity.WATER},
	{ID = Zone.neighborhood, Affinity = affinity.WATER},
	{ID = Zone.nektropos, Affinity = affinity.WATER},
	{ID = Zone.nektulos, Affinity = affinity.WATER},
	{ID = Zone.nektulosa, Affinity = affinity.WATER},
	{ID = Zone.neriaka, Affinity = affinity.WATER},
	{ID = Zone.neriakb, Affinity = affinity.WATER},
	{ID = Zone.neriakc, Affinity = affinity.WATER},
	{ID = Zone.neriakd, Affinity = affinity.WATER},
	{ID = Zone.netherbian, Affinity = affinity.WATER},
	{ID = Zone.nexus, Affinity = affinity.WATER},
	{ID = Zone.nightmareb, Affinity = affinity.WATER},
	{ID = Zone.northkarana, Affinity = affinity.WATER},
	{ID = Zone.northro, Affinity = affinity.WATER},
	{ID = Zone.nro, Affinity = affinity.WATER},
	{ID = Zone.nurga, Affinity = affinity.WATER},
	{ID = Zone.oasis, Affinity = affinity.WATER},
	{ID = Zone.oceangreenhills, Affinity = affinity.WATER},
	{ID = Zone.oceangreenvillage, Affinity = affinity.WATER},
	{ID = Zone.oceanoftears, Affinity = affinity.WATER},
	{ID = Zone.oggok, Affinity = affinity.WATER},
	{ID = Zone.oldblackburrow, Affinity = affinity.WATER},
	{ID = Zone.oldbloodfield, Affinity = affinity.WATER},
	{ID = Zone.oldcommons, Affinity = affinity.WATER},
	{ID = Zone.olddranik, Affinity = affinity.WATER},
	{ID = Zone.oldfieldofbone, Affinity = affinity.WATER},
	{ID = Zone.oldhighpass, Affinity = affinity.WATER},
	{ID = Zone.oldkaesoraa, Affinity = affinity.WATER},
	{ID = Zone.oldkaesorab, Affinity = affinity.WATER},
	{ID = Zone.oldkithicor, Affinity = affinity.WATER},
	{ID = Zone.oldkurn, Affinity = affinity.WATER},
	{ID = Zone.oot, Affinity = affinity.WATER},
	{ID = Zone.overthere, Affinity = affinity.WATER},
	{ID = Zone.paineel, Affinity = affinity.WATER},
	{ID = Zone.paludal, Affinity = affinity.WATER},
	{ID = Zone.paw, Affinity = affinity.WATER},
	{ID = Zone.pellucid, Affinity = affinity.WATER},
	{ID = Zone.permafrost, Affinity = affinity.WATER},
	{ID = Zone.pillarsalra, Affinity = affinity.WATER},
	{ID = Zone.poair, Affinity = affinity.WATER},
	{ID = Zone.podisease, Affinity = affinity.WATER},
	{ID = Zone.poeartha, Affinity = affinity.WATER},
	{ID = Zone.poearthb, Affinity = affinity.WATER},
	{ID = Zone.pofire, Affinity = affinity.WATER},
	{ID = Zone.poinnovation, Affinity = affinity.WATER},
	{ID = Zone.pojustice, Affinity = affinity.WATER},
	{ID = Zone.poknowledge, Affinity = affinity.WATER},
	{ID = Zone.ponightmare, Affinity = affinity.WATER},
	{ID = Zone.postorms, Affinity = affinity.WATER},
	{ID = Zone.potactics, Affinity = affinity.WATER},
	{ID = Zone.potimea, Affinity = affinity.WATER},
	{ID = Zone.potimeb, Affinity = affinity.WATER},
	{ID = Zone.potorment, Affinity = affinity.WATER},
	{ID = Zone.potranquility, Affinity = affinity.WATER},
	{ID = Zone.povalor, Affinity = affinity.WATER},
	{ID = Zone.powar, Affinity = affinity.WATER},
	{ID = Zone.powater, Affinity = affinity.WATER},
	{ID = Zone.precipiceofwar, Affinity = affinity.WATER},
	{ID = Zone.provinggrounds, Affinity = affinity.WATER},
	{ID = Zone.qcat, Affinity = affinity.WATER},
	{ID = Zone.qey2hh1, Affinity = affinity.WATER},
	{ID = Zone.qeynos, Affinity = affinity.WATER},
	{ID = Zone.qeynos2, Affinity = affinity.WATER},
	{ID = Zone.qeytoqrg, Affinity = affinity.WATER},
	{ID = Zone.qinimi, Affinity = affinity.WATER},
	{ID = Zone.qrg, Affinity = affinity.WATER},
	{ID = Zone.qvic, Affinity = affinity.WATER},
	{ID = Zone.qvicb, Affinity = affinity.WATER},
	{ID = Zone.rage, Affinity = affinity.WATER},
	{ID = Zone.ragea, Affinity = affinity.WATER},
	{ID = Zone.rathechamber, Affinity = affinity.WATER},
	{ID = Zone.rathemtn, Affinity = affinity.WATER},
	{ID = Zone.redfeather, Affinity = affinity.WATER},
	{ID = Zone.relic, Affinity = affinity.WATER},
	{ID = Zone.resplendent, Affinity = affinity.WATER},
	{ID = Zone.riftseekers, Affinity = affinity.WATER},
	{ID = Zone.rivervale, Affinity = affinity.WATER},
	{ID = Zone.riwwi, Affinity = affinity.WATER},
	{ID = Zone.roost, Affinity = affinity.WATER},
	{ID = Zone.rubak, Affinity = affinity.WATER},
	{ID = Zone.ruja, Affinity = affinity.WATER},
	{ID = Zone.rujb, Affinity = affinity.WATER},
	{ID = Zone.rujc, Affinity = affinity.WATER},
	{ID = Zone.rujd, Affinity = affinity.WATER},
	{ID = Zone.ruje, Affinity = affinity.WATER},
	{ID = Zone.rujf, Affinity = affinity.WATER},
	{ID = Zone.rujg, Affinity = affinity.WATER},
	{ID = Zone.rujh, Affinity = affinity.WATER},
	{ID = Zone.ruji, Affinity = affinity.WATER},
	{ID = Zone.rujj, Affinity = affinity.WATER},
	{ID = Zone.runnyeye, Affinity = affinity.WATER},
	{ID = Zone.sarithcity, Affinity = affinity.WATER},
	{ID = Zone.scarlet, Affinity = affinity.WATER},
	{ID = Zone.sebilis, Affinity = affinity.WATER},
	{ID = Zone.sepulcher, Affinity = affinity.WATER},
	{ID = Zone.shadeweaver, Affinity = affinity.WATER},
	{ID = Zone.shadowhaven, Affinity = affinity.WATER},
	{ID = Zone.shadowrest, Affinity = affinity.WATER},
	{ID = Zone.shadowspine, Affinity = affinity.WATER},
	{ID = Zone.shardslanding, Affinity = affinity.WATER},
	{ID = Zone.sharvahl, Affinity = affinity.WATER},
	{ID = Zone.shiningcity, Affinity = affinity.WATER},
	{ID = Zone.shipmvm, Affinity = affinity.WATER},
	{ID = Zone.shipmvp, Affinity = affinity.WATER},
	{ID = Zone.shipmvu, Affinity = affinity.WATER},
	{ID = Zone.shippvu, Affinity = affinity.WATER},
	{ID = Zone.shipuvu, Affinity = affinity.WATER},
	{ID = Zone.shipworkshop, Affinity = affinity.WATER},
	{ID = Zone.silyssar, Affinity = affinity.WATER},
	{ID = Zone.sirens, Affinity = affinity.WATER},
	{ID = Zone.skyfire, Affinity = affinity.WATER},
	{ID = Zone.skylance, Affinity = affinity.WATER},
	{ID = Zone.skyshrine, Affinity = affinity.WATER},
	{ID = Zone.sleeper, Affinity = affinity.WATER},
	{ID = Zone.sncrematory, Affinity = affinity.WATER},
	{ID = Zone.snlair, Affinity = affinity.WATER},
	{ID = Zone.snplant, Affinity = affinity.WATER},
	{ID = Zone.snpool, Affinity = affinity.WATER},
	{ID = Zone.soldunga, Affinity = affinity.FIRE},
	{ID = Zone.soldungb, Affinity = affinity.FIRE},
	{ID = Zone.soldungc, Affinity = affinity.FIRE},
	{ID = Zone.solrotower, Affinity = affinity.FIRE},
	{ID = Zone.soltemple, Affinity = affinity.FIRE},
	{ID = Zone.solteris, Affinity = affinity.WATER},
	{ID = Zone.somnium, Affinity = affinity.WATER},
	{ID = Zone.southkarana, Affinity = affinity.WATER},
	{ID = Zone.southro, Affinity = affinity.WATER},
	{ID = Zone.sro, Affinity = affinity.WATER},
	{ID = Zone.sseru, Affinity = affinity.WATER},
	{ID = Zone.ssratemple, Affinity = affinity.WATER},
	{ID = Zone.steamfactory, Affinity = affinity.WATER},
	{ID = Zone.steamfont, Affinity = affinity.WATER},
	{ID = Zone.steamfontmts, Affinity = affinity.WATER},
	{ID = Zone.steppes, Affinity = affinity.WATER},
	{ID = Zone.stillmoona, Affinity = affinity.WATER},
	{ID = Zone.stillmoonb, Affinity = affinity.WATER},
	{ID = Zone.stonebrunt, Affinity = affinity.WATER},
	{ID = Zone.stonehive, Affinity = affinity.WATER},
	{ID = Zone.stonesnake, Affinity = affinity.WATER},
	{ID = Zone.suncrest, Affinity = affinity.WATER},
	{ID = Zone.sunderock, Affinity = affinity.WATER},
	{ID = Zone.swampofnohope, Affinity = affinity.WATER},
	{ID = Zone.tacvi, Affinity = affinity.WATER},
	{ID = Zone.taka, Affinity = affinity.WATER},
	{ID = Zone.takb, Affinity = affinity.WATER},
	{ID = Zone.takc, Affinity = affinity.WATER},
	{ID = Zone.takd, Affinity = affinity.WATER},
	{ID = Zone.take, Affinity = affinity.WATER},
	{ID = Zone.takf, Affinity = affinity.WATER},
	{ID = Zone.takg, Affinity = affinity.WATER},
	{ID = Zone.takh, Affinity = affinity.WATER},
	{ID = Zone.taki, Affinity = affinity.WATER},
	{ID = Zone.takishruins, Affinity = affinity.WATER},
	{ID = Zone.takishruinsa, Affinity = affinity.WATER},
	{ID = Zone.takj, Affinity = affinity.WATER},
	{ID = Zone.templeveeshan, Affinity = affinity.WATER},
	{ID = Zone.tenebrous, Affinity = affinity.WATER},
	{ID = Zone.thalassius, Affinity = affinity.WATER},
	{ID = Zone.theater, Affinity = affinity.WATER},
	{ID = Zone.theatera, Affinity = affinity.WATER},
	{ID = Zone.thedeep, Affinity = affinity.WATER},
	{ID = Zone.thegrey, Affinity = affinity.WATER},
	{ID = Zone.thenest, Affinity = affinity.WATER},
	{ID = Zone.thevoida, Affinity = affinity.WATER},
	{ID = Zone.thevoidb, Affinity = affinity.WATER},
	{ID = Zone.thevoidc, Affinity = affinity.WATER},
	{ID = Zone.thevoidd, Affinity = affinity.WATER},
	{ID = Zone.thevoide, Affinity = affinity.WATER},
	{ID = Zone.thevoidf, Affinity = affinity.WATER},
	{ID = Zone.thevoidg, Affinity = affinity.WATER},
	{ID = Zone.thuledream, Affinity = affinity.WATER},
	{ID = Zone.thulehouse1, Affinity = affinity.WATER},
	{ID = Zone.thulehouse2, Affinity = affinity.WATER},
	{ID = Zone.thulelibrary, Affinity = affinity.WATER},
	{ID = Zone.thundercrest, Affinity = affinity.WATER},
	{ID = Zone.thurgadina, Affinity = affinity.WATER},
	{ID = Zone.thurgadinb, Affinity = affinity.WATER},
	{ID = Zone.timorous, Affinity = affinity.WATER},
	{ID = Zone.tipt, Affinity = affinity.WATER},
	{ID = Zone.torgiran, Affinity = affinity.WATER},
	{ID = Zone.toskirakk, Affinity = affinity.WATER},
	{ID = Zone.tox, Affinity = affinity.WATER},
	{ID = Zone.toxxulia, Affinity = affinity.WATER},
	{ID = Zone.trakanon, Affinity = affinity.WATER},
	{ID = Zone.tutorial, Affinity = affinity.WATER},
	{ID = Zone.tutoriala, Affinity = affinity.WATER},
	{ID = Zone.tutorialb, Affinity = affinity.WATER},
	{ID = Zone.twilight, Affinity = affinity.WATER},
	{ID = Zone.txevu, Affinity = affinity.WATER},
	{ID = Zone.umbral, Affinity = affinity.WATER},
	{ID = Zone.underquarry, Affinity = affinity.WATER},
	{ID = Zone.unrest, Affinity = affinity.WATER},
	{ID = Zone.uqua, Affinity = affinity.WATER},
	{ID = Zone.valdeholm, Affinity = affinity.WATER},
	{ID = Zone.veeshan, Affinity = affinity.WATER},
	{ID = Zone.veksar, Affinity = affinity.WATER},
	{ID = Zone.velketor, Affinity = affinity.WATER},
	{ID = Zone.vergalid, Affinity = affinity.WATER},
	{ID = Zone.vexthal, Affinity = affinity.WATER},
	{ID = Zone.vxed, Affinity = affinity.WATER},
	{ID = Zone.wakening, Affinity = affinity.WATER},
	{ID = Zone.wallofslaughter, Affinity = affinity.WATER},
	{ID = Zone.warrens, Affinity = affinity.WATER},
	{ID = Zone.warslikswood, Affinity = affinity.WATER},
	{ID = Zone.weddingchapel, Affinity = affinity.WATER},
	{ID = Zone.weddingchapeldark, Affinity = affinity.WATER},
	{ID = Zone.well, Affinity = affinity.WATER},
	{ID = Zone.westkorlach, Affinity = affinity.WATER},
	{ID = Zone.westkorlacha, Affinity = affinity.WATER},
	{ID = Zone.westkorlachb, Affinity = affinity.WATER},
	{ID = Zone.westkorlachc, Affinity = affinity.WATER},
	{ID = Zone.westsepulcher, Affinity = affinity.WATER},
	{ID = Zone.westwastes, Affinity = affinity.WATER},
	{ID = Zone.windsong, Affinity = affinity.WATER},
	{ID = Zone.xorbb, Affinity = affinity.WATER},
	{ID = Zone.yxtta, Affinity = affinity.WATER},
	{ID = Zone.zhisza, Affinity = affinity.WATER},
}

---@return number # 0: none, 1: spirit (magic), 2: fire, 3: water (cold), 4: (poison), 5: air (disease)
function Mob:AffinityDefense()
	local client = self:CastToClient()
	if client ~= nil and client.valid then
		-- TODO: add augs that change defensive affinity
		return deityAffinity(client:GetDeity())
	end

	local npc = self:CastToNPC()
	if npc == nil or not npc.valid then
		return affinity.NONE
	end

	return npc_affinity(eq.get_zone_id(), npc:GetRace(), npc:GetTexture())
end

function Mob:AffinityOffense()
	local client = self:CastToClient()
	if client ~= nil and client.valid then
		-- TODO: add augs that change offensive affinity
		return deityAffinity(client:GetDeity())
	end

	local npc = self:CastToNPC()
	if npc == nil or not npc.valid then
		return affinity.NONE
	end

	return npc_affinity(eq.get_zone_id(), npc:GetRace(), npc:GetTexture())
end

---@param zone_id number # zone ID
---@param race_id number # race ID
---@param texture_id number # texture ID
function npc_affinity(zone_id, race_id, texture_id)
	if zone_id == Zone.sebilis and race_id == race_name.Dragon then return affinity.EARTH end -- Trakanon

	local zone_affinity = ZoneAffinity[zone_id]
	if zone_affinity ~= nil then
		return zone_affinity.Affinity
	end
end
